---
title: "CADA writing notes"
output: html_notebook
---

**Active learning is social**

- Hypothesis: the social context can change the cost/benefit structure of choices made for learning and therefore we must include this information in our models of self-directed learning, which often view the learner as moving back and forth between active exploration and passive reception. This type of active learning account does not leave room for social reasoning processes (i.e., native utility calculus stuff) to change the value of an active learning behavior.
- Effective active learning involves generating the best evidence relative to your current state (hypotheses, cognitive resources, time, and goals). 
- Note that there's an interesting distinction between active learning behaviors that directly affect social targets (or are directed towards social targets) such as questions and social referencing compated to active learning behaviors that might be changed by the presence of a social partner or being in a communicative context such as gaze patterns to explore the visual world or motor behaviors to explore a new toy.

**Social learning is active**

- Hypothesis: Social interactions that yield information can productively be construed as active learning. 
- Teaching is providing opportunities for learner to engage in effective active learning.
- Inference about inferences, or what would other people learn given their hypothesis and some evidence. Teaching as inverting the active learning process of another. 
- Effective active learning involves generating the best evidence relative to your current state (hypotheses, cognitive resources, time, and goals). 

**Active information gathering via fixations during language learning**



Why should we care about the conversational context?

What does a converstation look like? What behaviors are available? How are they changed by the social context?

## Behavior 1: speaker choice

### Utility analysis
### Ecological opportunity

## Behavior 2: visual/auditory attention (integrating between success and failures)

### Utility analysis
### Ecological opportunity

## Behavior 3: questions (why didn't questions get asked in this setting?) --> Markman et al. 

### Utility analysis
### Ecological opportunity