---
title: "Children's active learning is social: how social contexts shape learners' choices"
short-title: "Active learning is social"
output: kmr::apa_manuscript
csl: apa6.csl
bibliography: library.bib
document-params: "a4paper,man,apacite,floatsintext"
author-information:
    - \author{Kyle MacDonald}
affiliation-information:
    # Single affiliation
    - \affiliation{Department of Psychology, Stanford University}
author-note:
    "Conceptual Analysis of Dissertation Area. Readers: Michael C. Frank, Hyowon Gweon, and Anne Fernald"
abstract: 
    "Children's rapid conceptual development is one of the more remarkable features of human cognition. How do they learn so much so quickly? Social learning theories argue for the importance of learning from more knowledgeable others. In contrast, active learning accounts focus on children's learning via exploration and the testing of hypotheses. In this paper, I argue that an important step towards a complete theory of human learning is to understand how active learning behaviors unfold within fundamentally social learning contexts. To integrate the two accounts, I use a framework of rational decision making that emphasizes the role of utility (i.e., costs and benefits of an action) for explaining choice behavior. The key insight is that social learning is not separate from active learning, and the costs/benefits of children' decisions about what to learn are shaped by interactions with other people."

keywords:
  "human learning, active learning, social learning, decision making, theory"
---

```{r global_options, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(fig.path='figs/', echo=F, warning=F, cache=T, message=F, sanitize=T)
library(tidyverse); library(knitr)
```

# Introduction 

Human learning is remarkable. Consider that children, despite striking limitations in their general processing capabilities, are able to acquire new concepts at a high rate eventually reaching an adult vocabulary ranging between 50,000 to 100,000 words [@bloom2002children]. And they accmplish this while also developing motor skills, learning social norms, and building causal knowledge. What sorts of processes can account for children's prodigious learning abilities?  

Social learning theories offer a solution by pointing out that children do not solve these problems on their own. And although children learn a great deal from observation, they are typically surrounded by parents, other knowledgeable adults, or older peers – all of whom likely know more than they do. These social contexts can bootstrap learning via several mechanisms. For example, work on early language acquisition shows that social partners provide input that is tuned to children's cognitive abilities [@fernald1987acoustic; @eaves2016infant], that guides children's attention to important features in the world [@yu2007unified], and that increases levels of arousal and sustained attention, which lead to better learning [@yu2016social; @kuhl2007speech]. 

Social contexts can also change the computations that support children' learning from evidence. Recent work on both concept learning and causal intervention suggests that the presence of another person leads the learner to reason about *why* people perform certain actions. The key insight is that knowledge of the underlying process that generates examples allows learners to make more appropriate inferences that speed learning [@frank2009using; @bonawitz2016computational; @shafto2014rational]. For example, people will draw different inferences from observing the same actions depending on whether they think that the behavior was accidental or intentional. Moreover, adults and children will make even stronger inferences if they think an action was selected with the goal to help them learn (i.e., teaching) [@shafto2012learning].

However, children are not passive recipients of information -- from people or from the world. Instead, children actively select behaviors (e.g., ask questions, choose where to allocate attention) that modulate the content, pacing, and sequence of information they receive. In fact, recent theorizing and empirical work in cognitive development characterizes early learning as an active process of exploration and hypothesis testing similar to the scientific method [@gopnik1999scientist; @schulz2012origins]. Moreover, recent empirical work across a variety of domains (education, machine learning, and cognitive science) has begun to explore the benefits of self-directed choice for speeding learning outcomes via an increase in attention/arousal or by providing better information that is more tightly linked to learners' current cognitive state and interests [@settles2012active; @castro2009human; @markant2014better].

Both social and active contexts facilitate cognitive development by activating distinct learning processes and by providing the learner with better information. However, real-world learning is not neatly divided into active and social contexts, but instead involves a mixture of these processes that unfold in dynamic environments.  Thus, one of the fundamental challenge for understanding human learning is to precisely characterize the interaction between social learning contexts and children's developing ability to exert control over their environments. 

In this paper, I propose that the framework of Bayesian rational decision making (CITE) is a productive way to integrate ideas from both the active and social learning accounts. The key insight is that social learning contexts can be construed as opportunities for *constrained active learning* where both learners and teachers make decisions about what to do whil also reasoning about the costs and benefits of those actions for themselves and for their social partner. I argue that considering how the presence of other people changes the cost-benefit calculus of choosing (costly) active learning processes provides a way to explain a diverse set of findings on children's uncertainty monitoring (markman; kim et al.), information seeking (begus), and question asking (katz et al. (2010). However, before presenting the integrative framework of active learning within social contexts, it is useful to review evidence showing how social and active processes can impact learning outcomes.

# Part I: Learning from other people

Social learning theories argue that a key factor in children's rapid conceptual development is humans' unique capacity to transmit and acquire information from other people. ^[In this paper, I define "social" contexts as learning environments where another agent is present. This definition includes a broad range of social learning behaviors: e.g., observation, imitation, and learning from direct pedagogy.] One of the primary benefits of this cultural learning process is that learners gain access to knowledge that has accumulated over many generations: information that would be far too complex for any individual to figure out on their own [@boyd2011cultural]. Moreover, social contexts can facilitate learning because more knowledgable others can select input to best support children's learning [@shafto2012learning; @kline2015learn], providing learning opportunities for generalizable information [@csibra2009natural].

A large body of empirical work on children's learning shows the effect of social contexts across a variety of learning domains. However, these effects manifest via different pathways such as guiding attention, increasing arousal, selecting better information, and changing the strength of children's inferences. In this section, I review the evidence for the role of each of these social learning processes, with the goal of providing a high-level taxonomy of social learning effects.   

### Social interactions enhance attention

From infancy, humans preferentially attend to social information. For example, newborn infants prefer to look at face-like patterns compared to other configurations [@johnson1991newborns] and will even show a preference for faces that make direct eye contact compared to faces with averted gaze [@farroni2002eye]. In the auditory domain, newborns prefer to listen to speech over non-speech [@vouloumanos2007listening], their mother's voice over other voices [@decasper1987human], and infant-directed speech over adult-directed speech [@cooper1990preference; @pegg1992preference; @fernald1987acoustic]. Moreover, recent work by @yu2016social used head-mounted eye trackers to record parent-child interactions and found that one-year-olds will sustain visual attention to an object longer when their parents' had previously looked at that object.

These attentional biases lead to different outcomes in social learning contexts. For example, 4-month-olds' show better memory for faces if that face gazed directly at them as compared to a face with averted gaze  [@farroni2007direct]. 4-month-olds' memory for objects is enhanced if an adult gazed at that object during learning [@reid2005adult; @cleveland2007joint]. And 7-month-olds more easily segment words from infant-directed speech compared to adult-directed speech [@thiessen2005infant].

@kuhl2007speech refer to these effects as "social gating" phenomena since the presence of another person activates or enhances children's computational learning mechanisms. One particularly striking piece of evidence for the social gating hypothesis comes from @kuhl2003foreign's study of infants' foreign-language phonetic learning. In this experiment, 9-10 month-old English-learning infants listened to Mandarin speakers either via live interactions or via audiovisual recordings and their ability to discriminate Mandarin-specific phonemes was assessed two months later. Only the infants who were exposed to Mandarin within social interactions were able to succeed on the phonetic discrimination task and infants in the audiovisual recording condition showed no evidence of learning. @kuhl2003foreign also provided evidence that infants in the social interaction condition showed higher rates of visual attention to the speaker, suggesting that the social contexts enhanced learning by increasing children's attention to the input.

The common thread across these findings is that the presence of another person is a particularly good way to increase attention. In this model, social input becomes more salient and therefore more likely to come into contact with children's general learning mechanisms. However, increases in arousal, attention, and memory are only one way that social contexts can influence learning. In fact, one of the defining features of early learning environments is the presence of other people who know more than the child. This creates opportunities for more knowledgable others to select learning experiences that are particularly beneficial -- either because the information is tuned to children's current cognitive abilities or because the information is likely to be generalizable. 

### Social interactions provide "good" information

The notion that children's input might be shaped to facilitate their learning is a key tenet of several influential theories of cognitive development (e.g., Zone of Proximal Development [@vygotsky1987zone], Guided Participation [@rogoff1993guided], and Natural Pedagogy [@csibra2009natural]). But how do social interactions provide particularly useful information for children's learning? 

A particularly compelling set of evidence comes from studies of how caregivers alter the way they communicate with young children. That is, adults do not speak to children in the same way as they speak to other adults; instead, they exaggerate prosody, reduce speed, shorten utterances, and elevate both pitch and affect (for a review, see [@fernald1984expanded]). And subsequent empirical work has shown that these features of "infant-directed speech" facilitate vowel learning [@adriaans2017prosodic; @de2003investigating], word segmentation [@fernald1991prosody; @thiessen2005infant], word recognition [@singh2009influences], and word learning [@graf2013infant]. 

Work on infants' early vocal production also provides evidence for the importance social feedback, highlighting the feature of *contingency*. For example, @goldstein2008social measured whether infants modified their babbling to produce more speechlike sounds after interacting with caregivers who either provided contingent or non-contingent responses to infants' babbling. They found that only infants in the contingent feedback condition changed their vocalization behavior to produce more adult-like language forms. @goldstein2008social hypothesized that the contingency effect was driven by infants' receiving input that was particularly useful for solving this learning problem since the feedback was close in time to infants' vocalizations, making it easier for them to compare discrepancies between the two. 

A third piece of evidence comes from research on children's early word learning. Social-pragmatic theories of language acquisition have emphasized the importance of social cues for reducing the (in principle) unlimited amount of referential uncertainty present when children are trying to acquire novel words [@bloom2002children; @clark2009first; @hollich2000breaking]. Empirical work by @yu2012embodied shows that young learners tend to retain words that are accompanied by clear referential cues, which serve to make a single object dominant in the visual field (see also [@yu2013joint; @yu2005role]. Moreover, correlational studies show positive links between early vocabulary development and parents' tendency to refer to objects that children are already attending to (i.e., "follow-in" labeling) [@tomasello1986joint].

Thus far, I have reviewed evidence showing that social information can benefit learning because it (a) enhances attention and it contains features that make it easier to learn. Learning from other people also changes learning by engaging distinct social reasoning processes that change how learners interpret and learn from evidence.

### Social interactions change inferences and generalization

Perhaps one of the defining features of human social learning is that teachers and learners' actions are not random. Instead, people select behaviors with respect to some goal (e.g., to communicate a concept), and learners reason about *why* someone chose to perform a particular action. The key point is that this reciprocal process of reasoning about others' goal-directed actions can change how people interpret superficially similar behaviors, altering the learning process. 

In recent empirical and modeling work, @shafto2012learning formalized this social reasoning process within the framework of Bayesian models of cognition. In these models, learning is a process of belief updating that depends on two factors: what the learner believed before seeing the data and what the learner thinks about the process that generated the data. The key insight is that if the learner assumes that information is generated with the intention to communicate/teach, then they can make "stronger" inferences. ^[Formally, these models change the form of the likelihood term in Bayes theorem in order to capture a person’s theory of how data are generated.]

For example, @goodman2009cause presented adults with causal learning scenarios with the following structure: either the participant or someone else who knows the causal structure generates an effect (e.g., growing flowers) by performing two actions at the same time (e.g., pouring a yellow liquid and a blue liquid). The participant's task was to identify the correct causal structure. Results showed that when participants thought the other person was knowledgable, they were more likely to infer that performing *both* actions was necessary. In contrast, when the participant performed the action on their own (and did not know the causal structure), adults were less sure that both actions were necessary. @shafto2012learning interpreted these results as learners going through a psychological reasoning process such as "if the other person was knowledgeable and wanted to generate the effect, he would definitely perform both actions if that was the correct causal structure."

Similar psychological reasoning effects have been shown in the domains of word learning [@xu2007word; @frank2014inferring], selective trust in testimony [@shafto2012epistemic], tool use [@sage2011disentangling], and concept learning [@shafto2014rational]. Moreover, there is evidence that even very young learners are sensitive to the presence of others' goal-directed behaviors. For example, @yoon2008communication showed that 8-month-olds will encode an object's identity if their attention was directed by a communicative point, but they will encode an object's spatial location if their attention was directed by non-communicative reach. And @senju2008gaze found that infants will follow another person's gaze only if the gaze event was preceded by the person providing a relevant, communicative cue (e.g., infant-directed speech or direct eye contact). 

In addition to being easier to learn, information acquired in social contexts is also more likely to generalize and be useful beyond the current learning context. @csibra2009natural argue that this assumption of *generalizability* is a fundamental component of "Natural Pedagogy" -- a uniquely human communication system that allows adults to efficiently pass along cultural knowledge to children. Experimental work testing predictions from this account shows that children are biased to think that information presented in communicative contexts is generalizable [@yoon2008communication; @butler2012preschoolers], and corpus analyses provide evidence that generic language (e.g., "birds fly") is common in everyday adult-child conversations [@gelman2008generic]. 

For example, [natural pedagogy study here]

Across all of these studies, learners interpreted similar information in very different ways depending on their assumptions about other people's goals. These effects are different from the attentional and informational explanations reviewed above in that the inferences based on social information are part of the underlying computations that support learning. This account fits well with evolutionary models that emphasize the importance of pedagogy for the accumulation of human cultural knowledge [@kline2015learn; @boyd2011cultural] and theories of cognitive development that emphasize the adult's role as providing children with generalizable information [@csibra2009natural].

# Part II: Learning on your own 

A great deal of early learning occurs within social contexts where other people shape the learning experience. But children are not just passive recipients of information from the world; instead, they actively seek information via their own actions and choices. This model of the child as an "active" learner has been an influential idea in many classic theories of cognitive development (e.g., @bruner1961act; @berlyne1960conflict; and piaget_cite). Moreover, recent theorizing has characterized cognitive development as a process of active hypothesis testing and theory revision similar to principles of the scientific method [@schulz2012origins; @gopnik1999scientist].  

In addition to playing a prominent role in developmental theory, the potential benefits of "active"[^1] learning have been the focus of a great deal of empirical work in education [@grabinger1995rich; @prince2004does], machine learning [@settles2012active; @ramirez2017active], and cognitive psychology [@castro2009human; @chi2009active]. The common finding across these studies is that active learning contexts -- where people have control over some aspect of the envrionment -- lead to better learning outcomes when compared to passive contexts where people do not have control over the information that they receive from the world. 

But what makes active control such a powerful way to learn about the world? In this section, I present the evidence for two mechanisms -- enhanced attention/memory and higher quality information -- through which active control can change learning outcomes in both adults and children. 

[^1]: The term "active learning" has been used to describe a wide variety of behaviors such as question asking, increased physical activity, or active memory retrieval. In this paper, I focus on a specific subset of these behaviors: the *decisions* that people make, or could make, during learning. This definition captures several ways that people can exert control over their learning experiences, including the selection, sequencing, and/or pacing of new information. 

### Active control enhances attention and memory

A growing body of work has explored the effect of active control on basic processes underlying learning and memory. In these tasks, outcomes for active and passive learning experiences are directly compared across a variety of tasks, such as episodic memory, casual learning, and concept learning. @markant2016enhanced review this diverse literature and suggest that the active learning advantage found across these domains is caused by an increase in attention and memory with the precise pathway determined by the type of control in the study. For example, one effect of active control is that is allows people to coordinate the timing of incoming information with their current cognitive state, including attention and readiness to learn. 

One nice illustration of this effect comes from a study by @markant2014deconstructing. In this task, participants memorized the identities and locations of objects that were hidden in a grid (adapted from @voss2011spontaneous). @markant2014deconstructing varied the *level* of control across conditions and compared the performance of active learners to a group of "yoked" participants who saw training data that was generated by the active group. Across conditions, participants could either control: (a) the next location in the grid, (b) the next item to be revealed, (c) the duration of each learning trial, and/or (d) the time between learning trials (i.e., inter-stimulus-interval or ISI). Results showed an active learning advantage for all levels of control, including the lowest amount of control in the ISI-only condition. @markant2014deconstructing interpreted these results as providing evidence that active control allowed people to, "optimize their experience with respect to short-term fluctuations in their own motivational or attentional state."

Recent developmental studies have extended this work on adults' spatial memory to 6- to 8-year old children, showing similar advantages for conditions of active control [@ruggeri2016active]. Other work has found similar benefits of active control in word learning (@partridge2015young; see also @kachergis2013actively for evidence in adults) and understanding causal structures [@schulz2012origins]. Moreover, even very young infants benefit from active engagement with the environment. For example, @begus2014infants showed that 16-month-old infants learn better when information was provided about an object they had pointed to as opposed to an object they had previously ignored.

Additional evidence that active control enhances attention and memory comes from research on children's engagement with educational technology (for a review, see @hirsh2015putting). For example, @calvert2005control exposed preschool-aged chidren to two sessions of reading a computer storybook with an adult, and manipulated whether the adult or the child controlled the mouse and could advance the story. Children in the adult-control condition showed a decrease in attention to the storybook materials in the second session; in contrast, children who were given control over the experience maintained similar levels of attention across both sessions.

These studies parallel the literature reviewed in Section 1, showing the effects of social contexts on basic processes of attention and memory that facilitate in-the-moment learning. Similar to the effects of social learning, the benefits of active control operate through multiple mechanisms, going beyond changes in lower-level cognitive processes to changing the quality of *information* that learners get from the world. 

### Active control provides "good" information

Active learning allows people to gather information that is particularly "useful" for their own learning. This benefit relies on the fact that learners have better access to their own prior knowledge, current hypotheses, and ability level, which they can leverage to create more helpful learning contexts (e.g., asking a question about something that is particularly confusing).Research on this area of active learning focuses on how learners adaptively select the *content* of their learning experiences using a set of metacognitive monitoring skills. 

For example, @castro2009human directly compared human active and passive category learning to predictions from statistical learning theory under conditions of varying difficulty. They found that human active learning was always superior to passive learning, but did not reach the performance of the optimal model and the advantage for active control decreased in the more difficult (i.e., noisier) learning tasks. Using a similar approach, @markant2014better investigated the effects of active vs. passive hypothesis testing on the rate of adults’ category learning. They varied the difficulty of the learning task by testing two different types of category structures: a rule-based category, which varied along 1 dimension (easier to learn), and an information-integration category, which varied along 2 dimensions (harder to learn). In the active condition, the learner chose specific observations from the category to test his or her beliefs, whereas in passive condition, the data were generated randomly by the experiment. Participants in the active condition learned the category structure faster and achieved a higher overall accuracy rate compared to participants in the passive learning condition, but only for the simpler, rule-based category. 

Together, the @castro2009human and @markant2014better findings illustrate several important points about active learning benefits. First, the quality of active exploration was fundamentally linked to the the learner's understanding of the task: if the representation was poor, then self-directed learning was biased and ineffective.  Second, the benefits of active control are tied to the aspects of the individual learner -- prior knowledge, current hypotheses under consideration -- such that the same sequence of data might not provide "good" information for another learner. Third, the benefits of active learning diminished with increased difficulty of the learning problem, likely because learners could not generate helpful examples.

### What is missing from the active learning account?

Active learning in social contexts. The presence of another agent can change the cost/benefit structure of choices made for learning and therefore models of self-directed learning should include this information. In contrast, these models often view the learner as moving back and forth between active exploration and passive reception. This type of active learning account does not leave room for social reasoning processes (i.e., naive utility calculus, goal reasoning) to change the utility of active learning behaviors.

# Part III: Integrating social and active learning 

### Social information seeking 

Active social learning - seek information from social targets. Models of seeking information from social targets: 

    -  Baldwin & Moses (1998): The Ontogeny of Social Information gathering
    -  Chouinard (2007): Children's questions as learning mechanism
    -  Hyo's and Liz Bonawitz's work

These studies of the benefits of active information selection connect nicely to developmental work on children's question asking. Verbal questions are a spontaneous behavior that occurs in everyday interactions that could allow children to seek information that is directly relevant to their current interests and misconceptions. Moreover, asking a good question is complex: the child must know what they don’t know, how to ask about it, who to ask about it, and be able to assimilate new information. 

There is evidence that children from a young age use questions to gather information from other people. For example, in a corpus analysis of four children's parent-child conversations, @chouinard2007children found that children begin asking questions early in development (18 months) and at an impressive rate, ranging from 70-198 questions per hour of conversation. @chouinard2007children also coded the intent of children's questions, finding that 71% were for the purpose of gathering information, as opposed to attention getting or clarifications. Other corpus analyses provide converging evidence that question asking is a common behavior in parent-child conversations [@davis1932form], that children are seeking knowledge with their questions [@bova2013investigating, and that children will persist in asking questions if they do not recieve a satisfactory explanation [@frazier2009preschoolers]. 

Experimental work has investigated the quality of children's question asking by measuring the quality of questions in constrained problem-solving tasks. For example, @legare2013use used a modified question asking game where 4- to 6-year-old children saw 16 cards with a drawing of an animal on them. The animals varied along several dimensions, including type, size, and pattern on the animal. The child's task was to ask the experimenter yes-no questions in order to figure out which animal card the experimenter had hidden in a special box. @legare2013use coded whether children asked *constraint-seeking* questions that narrowed the set of possible cards by increasing knowledge of a particular dimension or dimensions (e.g., "Is it red?"), *confirmatory* questions that provided redundant information, or *ineffective* questions that did not provide any useful information (e.g., "Does it have a tail?"). Results showed that all age groups asked a higher proprotion of the effective, constraint-seeking questions relative to the other question types, and that the number of constraint-seeking questions was correlated with children's accuracy in guessing the identity of the card hidden in the special box. @legare2013use interpret these results as evidence that children can use questions to solve problems in a efficient manner. Converging evidence in support of this interpretation comes from experimental work using this approach finding that children prefer to direct questions to someone who is knowledgable compared to someone who is inaccurate or ignorant [@mills2011determining; @mills2010preschoolers], 

However, other work has focused on the social context in which question asking occurs. 

### Incorportating social reasoning in active learning 

Active learning takes into account a utility structure that can include both the costs of data acquisition and the rewards of choosing an example (e.g., in terms of information acquisition/uncertainty reduction relative to some longer term learning goal). 

Focusing on *choices* is useful since there is a rich literature that has formalized decision-making process, which can be used to describe behaviors made by both more knowledgeable others and by learners. The interesting question is how costs/benefits of active learning behaviors are altered by the social context and how reasoning about learners as active might change the social context.

Process:

    - analyze costs and benefits of behavior
    - planning models that take into account long-term value
    - decisions in the brain and in non-human primates 

# Conclusion

Models of self-directed learning should include information the social-communicative context in which learning often occurs. Reasoning about other people modulate the choices that learners make: whether it's who to talk to, what to look at, or what questions to ask.

Models of social learning should take into account the choice behaviors available to the learner. i.e., think about teaching as reasoning about another person's active learning or setting up a social learning context where the learner selects actions

\newpage

# References 

\setlength{\parindent}{-0.4in} 
\setlength{\leftskip}{0.125in}
\noindent
